### ISSUE TITLE
Include a demorepo config yml file

### ISSUE THREAD

**Issue by jcozar87** [demosense/demorepo#2]
The init command should create the metadata of the repo. You can edit the options / parameters of the demorepo using commands of init subparser. For now, until this command is fully implemented, manage the config.yml manually.

The file should include:

- Order dependencies for projects
- ...?

**Comment by jcozar87** [comment]
- ci-tool and url of the ci-tool. This should be the same most part of the time,  therefore it might be in the demorepo config too.

**Comment by jcozar87** [comment]
Until this issue is solved, using an ad-hoc created config.yml file. Refer to commit #4 to see the implemented structure.

**Comment by jacintoArias** [comment]
Perhaps the file should be called `demorepo-config.yml` or something like that... `config.yml` can crash with other utilities...

**Comment by jacintoArias** [comment]
That is a good point, we should decide if the file is autogenerated or it is hybrid and user can push changes as well (like in a package.json). There are some dangerous use cases when properties in this file must be synced with other tools such as git config. See #8 for a particular case.

**Comment by jacintoArias** [comment]
May I propose config file schema:

```
demorepo: 1.0.0

projects:
  p1:
    path: ./projects/p1
    type: submodule
  p2:
    path: ./projects/p2
    type: submodule
    depends_on: p1
```
