### ISSUE TITLE
Allow using a global demorepo.yml file

### ISSUE THREAD

**Issue by jacintoArias** [demosense/demorepo#25]
Individual subprojects shouldn't have to be aware of being managed by the demorepo tool. 

I propose configuring demorepo to use a global `demorepo.yml`  file in the root of the project to orchestrate the different projects.

There are two possible syntax:

B) Projects are explicitly specified for each stage
```
stage:
  script:
  projects:
   - projA

stage:
  script:
  projects:
    - proj A 
    - proj B
```

A) 
- Allows to have default stages without hardcoding for all projects 
- For groups of projects we can hardcode the targets with `only` or hardcode the exceptions with `except`

B) Everyrhing has to be hardcoded, so it is safer

Vote!
